profiles.adoc

In CSR `hstatus`, bits VTVM, VTW, and VTSR are always writable.  (If there's any doubt about that fact, a clarification is needed in the Privileged ISA document.)
CSR `htval` isn't written the same as `stval`, and there is no `htval2`.

Corrections for hypervisor extension

---

profiles.adoc

Sidenote: The glossary also does not mention user-level interrupts. The latest `riscv-spec.pdf` states
> Moved N extension for user-mode interrupts into Volume II.
yet `riscv-privileged.pdf` only mentions user-mode interrupts under its MISA table as
> Tentatively reserved for User-Level Interrupts extension
Thus it is unclear which document should be referenced, if any.

Add Zihpm, Sv57, Svpbmt, Svnapot, Svinval, Sstc, Sscofpmf, and Smstateen to glossary.

---

profiles.adoc

The toolchain community would like to embed profile names into the `-march=...` command line argument, which currently processes the RISC-V ISA naming string (as defined in the unpriv spec).
However, there are concerns that these two namespaces are different and therefore potentially conflicting in the future.
To clarify the situation, this change adds a note that the profile's namespace will be compatible with the RISC-V ISA naming string (i.e. there will be no standard extension that will have profile name).
Probably a similar change should be added to the riscv-isa-manual repo.

Naming: Adding note to clarify compatiblity with ISA naming strings

---

.github/workflows/build-pdf.yml
.github/workflows/create-release.yml

The build-pdf.yml workflow has been simplified to just build.  It's also been made callable (within project).  The calls for this action remain unchanged.
A new create-release.yml workflow has been added as a manual workflow option that can be used to build releases with a PDF.  The flow prompts for release name and a couple flag settings (draft and pre-release).  It uses the build-pdf.yml workflow to create the PDF.  Then, it builds the release and add the PDF in additional to the base artifacts.

Workflow updates for PDF building and Release Generation

---

profiles.adoc

...since it's a virtual-memory-related extension.
Resolves #81

Rename Ssptead to Svptead

---

profiles.adoc

The NOTE's claim that UXL=0 if writable-UXL is unsupported is inconsistent with the priv spec; it should be wired to 2 in this case.
Resolves #75

Fix the description of Ssu64xl

---

profiles.adoc
rva23-profile.adoc

*   Fixes some typos (general words and two extension names).
*   Because we didn't ratify `Zicntr` and `Zihpm` in 2022, it bumps the planned ratification year.

Small tidying (typos, year 2022 to 2023)

---

rvb23-profile.adoc

I do not think there was such a thing as *RVB22S64*:
- moving `Svnapot` from "mandatory in RVB22S64" (which did not exist I think) to newly mandatory (and also in `RVA23S64`)
- removing mention of *RVB22S64* and replace by the relevant mention of *RVA22S64*

removing RVB22S64 mentions

---

rva23-profile.adoc
rvb23-profile.adoc
rvm23-profile.adoc

Strip Zjpm from RVM, since RVM currently only defines the U-mode architecture, but S- or M-mode is needed to define pointer masking.
Update RVA23 to require Ssnpm with PMLEN=7 (see #130 for discussion).
Update RVB23 to make Ssnpm optional.
Resolves #130

Update profiles to reflect new pointer-masking extensions

---

rva23-profile.adoc

Removed Sdtrig as a required extension.
In order to allow maximum flexibility, the Debug specification defines Sdtirg with a single requirement: "If Sdtrig is implemented, the Trigger Module must support at least one trigger."
The Sdtrig mandates belong in platform specifications where specific requirements can be provided so that all complaint implementations will have a common base of debug support.
See [What is required for Sdtrig? #134](https://github.com/riscv/riscv-profiles/issues/134) for more details

Remove Sdtrig

---

rva23-profile.adoc

Closes #133. There hasn't been any discussion there, so I don't know if this change is actually wanted, but I wanted to make it as easy as possible for someone to click the merge button if so :) Here's a copy of the body of that issue:
> RVA23 currently mandates both Zkt and V, so it seems natural that it should also mandate Zvkt. Although the optional Zvkng and Zvksg extensions both imply Zvkt, high-performance implementations of a lot of software-oriented cryptography primitives (like ChaCha and Poly1305) depend only on V and Zvbb, and those implementations are likely to assume Zvkt even if it's not officially required.

require Zvkt in RVA23

---

rvb23-profile.adoc

- Improve the text, delineating what's new since RVA22U64.
- Mandate Zimop/Zcmop, since they're cheap and simplify the binary-compatibility story
- Make Ssnpm optional, rather than coupling it to the H extension (which I think was an editing error, since it seems illogical)

Tweaks to RVB23 profiles

---

profiles.adoc

Section 6.1.2 contains the statement 'The following mandatory extensions were present in RVA20U64.' followed by a list of extensions, including Zihpm. This statement is a little confusing as Zihpm is an optional extension in RVA20U64.
This commit aims to clear up any confusion by adding a note to section 6.2.1 mentioning that Zihpm was optional in RVA20U64.  This is similar to the note added in rva23-profile.adoc that clarifies the status of 'V' which is optional in RVA22U64 and mandatory in RVA23U64.

Note in RVA22U64 that Zihpm was optional in RVA20U64

---

rva23-profile.adoc

This PR probably needs an explanation for the choice of 16 bytes.  It also should be ported to RVB23.

Add option for 16-byte misaligned atomicity granule in RVA23

---

rva23-profile.adoc
rvb23-profile.adoc

Churn in the pointer-masking extensionology led us to inadvertently omit Sspm and Supm from the profiles; these were meant to be added at the same time that Ssnpm was added, with Supm's existence following from Ssnpm's existence and Sspm being an extension option.

Fix omission of Sspm and Supm from RVA23/RVB23

---

profiles.adoc
rva23-profile.adoc
rvb23-profile.adoc
rvm23-profile.adoc

Let's fix these typos so they won't be copied anymore.

Fix a couple of s/isf/is typos in the profiles

---

src/profiles.adoc
src/rva23-profile.adoc
src/rvb23-profile.adoc

Both illegal-instruction and virtual-instruction exceptions must populate stval with the faulting instruction.
This is not a change; the behavior was already mandated by the following clause in the hypervisor spec: https://github.com/riscv/riscv-isa-manual/blob/65c6b5d3e69cdc2bd2658f9639fd10553c4b34e0/src/hypervisor.adoc#L2040-L2041
We are replicating that information here for added clarity.

Clarify that Sstvala applies to virtual-instruction exceptions, too

---

src/rva23-profile.adoc
src/rvb23-profile.adoc

fixes prolog about where to find Ssstateen

Sssstateen is now incorporated into RISC-V ISA Manual (vol 2)

---

src/profiles.adoc
src/rva23-profile.adoc
src/rvb23-profile.adoc

No change to RVA22S64/RVA23S64/RVB23S64 semantics; just aiming for brevity.

Introduce Sha extension, which absorbs hypervisor mandates

---

src/profiles.adoc
src/rva23-profile.adoc
src/rvb23-profile.adoc

Conciseness is the goal.  These formulations are equivalent.

Use B extension in profiles, rather than Zba_Zbb_Zbs.

---

src/rvm23-profile.adoc

B was introduced as a shorthand for Zba+Zbb+Zbs. Follow the RVA22/RVA23/RVB23 profiles by using it in the RVM23 definition.

Use 'B' in the RVM23 profile definition

---

src/rva23-profile.adoc
src/rvb23-profile.adoc

These were renamed prior to ratification of the pointer-masking extensions, but we forgot to update the profiles accordingly.
Resolves #195

Rename xenvcfg.PME fields to PMM

---

Makefile
build_rvm23_profile
src/rvm23-profile.adoc

A few things:
- The RVM23 profile adoc file was not pointing to the proper logo
- The Makefile had double-quote protection around $(REVMARK) but not around $(VERSION) which becomes important for the next bullet
- If one simply adds rvm23-profile.adoc to the Makefile DOCS variable and does a build, one ends up with a spec that says it is ratified(!!!!!!!!). I added a script, `build_rvm23_profile`, that sets up several variables such that the VERSION ends up printing the actual version embedded in the .adoc file, embeds the git SHA into the VERSION string as well, and also sets REVMARK to "Draft" instead of "This document is in Ratified state."
There is supposed to be a way of setting REVMARK and VERSION in the Makefile based on the target, but I didn't see a way that was working for me …

RVM23 fixes: logo, Makefile tweaks, added script so that RVM23 profile docs build cleanly
